sudo: false
language: python
cache:
  directories:
  - "$HOME/.cache/pip"

matrix:
  include:
  - python: 3.7
    env: TOXENV=flake8

  - python: 3.7
    env: TOXENV=py37

install:
  - pip install pip tox codecov twine

script:
  - tox -e $TOXENV

after_success:
  - codecov
