matrix:
  include:
    - language: python
      python: "3.8"
      env: TOXENV=flake8
    - language: python
      python: "3.7"
      env: TOXENV=py37
    - language: python
      python: "3.8"
      env: TOXENV=py38
    - language: python
      python: "3.9"
      env: TOXENV=py39
    - language: python
      python: "3.10"
      env: TOXENV=py310
    - language: python
      python: "3.11"
      env: TOXENV=py311
    - language: python
      python: "3.12"
      env: TOXENV=py312

install:
    # Temp solution to multiprocessing travis issue #155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    - pip install tox codecov

script:
    - tox -v

after_success:
    - codecov

notifications:
    irc:
        channels:
            - "chat.freenode.net#specterframework"
        use_notice: true
        skip_join: true
